use crate::storage::preferences::resolve_data_dir;
use std::fs;
use std::path::PathBuf;

fn trends_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = resolve_data_dir(app)?.join("trend_analyses");
    fs::create_dir_all(&dir)
        .map_err(|e| format!("Cannot create trend analyses dir '{}': {e}", dir.display()))?;
    Ok(dir)
}

fn is_valid_id(id: &str) -> bool {
    !id.is_empty()
        && id.len() <= 128
        && id
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

/// Persist a trend analysis to disk. `id` must be alphanumeric/dash/underscore
/// (typically a timestamp-based slug generated by the frontend).
/// `data_json` is a serialised `TrendAnalysisRecord` from the frontend.
#[tauri::command]
pub fn save_trend_analysis(
    app: tauri::AppHandle,
    id: String,
    data_json: String,
) -> Result<(), String> {
    if !is_valid_id(&id) {
        return Err(format!("Invalid trend analysis id: {id}"));
    }
    let path = trends_dir(&app)?.join(format!("{id}.json"));
    fs::write(&path, data_json)
        .map_err(|e| format!("Cannot write trend analysis {id}: {e}"))
}

/// Load a previously saved trend analysis. Returns None when no file exists.
#[tauri::command]
pub fn load_trend_analysis(
    app: tauri::AppHandle,
    id: String,
) -> Result<Option<String>, String> {
    if !is_valid_id(&id) {
        return Err(format!("Invalid trend analysis id: {id}"));
    }
    let path = trends_dir(&app)?.join(format!("{id}.json"));
    if !path.exists() {
        return Ok(None);
    }
    let content = fs::read_to_string(&path)
        .map_err(|e| format!("Cannot read trend analysis {id}: {e}"))?;
    Ok(Some(content))
}

/// List all saved trend analysis IDs, sorted lexicographically (reverse-chronological
/// when IDs are timestamp-based).
#[tauri::command]
pub fn list_trend_analyses(app: tauri::AppHandle) -> Result<Vec<String>, String> {
    let dir = trends_dir(&app)?;
    let mut ids: Vec<String> = Vec::new();
    for entry in fs::read_dir(&dir)
        .map_err(|e| format!("Cannot read trend analyses dir: {e}"))?
    {
        let entry = entry.map_err(|e| format!("Dir read error: {e}"))?;
        let name = entry.file_name();
        let s = name.to_string_lossy();
        if let Some(stem) = s.strip_suffix(".json") {
            if is_valid_id(stem) {
                ids.push(stem.to_string());
            }
        }
    }
    ids.sort();
    ids.reverse();
    Ok(ids)
}

#[tauri::command]
pub fn delete_trend_analysis(
    app: tauri::AppHandle,
    id: String,
) -> Result<(), String> {
    if !is_valid_id(&id) {
        return Err(format!("Invalid trend analysis id: {id}"));
    }
    let path = trends_dir(&app)?.join(format!("{id}.json"));
    if path.exists() {
        fs::remove_file(&path)
            .map_err(|e| format!("Cannot delete trend analysis {id}: {e}"))?;
    }
    Ok(())
}
