import { Button } from "@/components/ui/button";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { getPreferences, setPreference } from "@/lib/preferences";
import { dataDirectoryHasContent, getDataDir, moveDataDirectory, relaunchApp } from "@/lib/tauri/misc";
import { cn } from "@/lib/utils";
import { ask as askDialog, open as openDialog } from "@tauri-apps/plugin-dialog";
import { revealItemInDir } from "@tauri-apps/plugin-opener";
import { AlertCircle, CheckCircle, FolderOpen, Loader2 } from "lucide-react";
import { useEffect, useState } from "react";
import { type SectionStatus } from "./_shared";

export function DataDirectorySection() {
  const [dir, setDir] = useState("");
  const [resolvedDir, setResolvedDir] = useState("");
  const [status, setStatus] = useState<SectionStatus>({
    state: "idle",
    message: "",
  });

  useEffect(() => {
    getPreferences().then((prefs) => setDir(prefs["data_dir"] ?? ""));
    getDataDir()
      .then(setResolvedDir)
      .catch(() => {});
  }, []);

  async function persist(next: string): Promise<string> {
    setStatus({ state: "loading", message: "" });
    try {
      await setPreference("data_dir", next);
      setDir(next);
      const resolved = await getDataDir();
      setResolvedDir(resolved);
      setStatus({
        state: "success",
        message: next ? "Saved" : "Reset to default",
      });
      return resolved;
    } catch (e) {
      setStatus({ state: "error", message: String(e) });
      throw e;
    }
  }

  async function applyDirectoryChange(targetPref: string) {
    const oldResolved = resolvedDir;
    let newResolved: string;
    try {
      newResolved = await persist(targetPref);
    } catch {
      return;
    }
    if (!oldResolved || newResolved === oldResolved) return;

    try {
      const hasContent = await dataDirectoryHasContent(oldResolved);
      if (hasContent) {
        const move = await askDialog(
          `Move your existing data from\n\n${oldResolved}\n\nto\n\n${newResolved}\n\n` +
            `Click "Yes" to move it across, or "No" to leave it behind and start fresh in the new location.`,
          { title: "Move existing data?", kind: "info" },
        );
        if (move) {
          setStatus({ state: "loading", message: "" });
          await moveDataDirectory(oldResolved, newResolved);
          setStatus({ state: "success", message: "Moved" });
        }
      }
    } catch (e) {
      setStatus({ state: "error", message: `Could not move data: ${e}` });
      return;
    }

    const restart = await askDialog(
      "Restart Meridian now so the new data directory takes effect?",
      { title: "Restart required", kind: "info" },
    );
    if (restart) {
      try {
        await relaunchApp();
      } catch (e) {
        setStatus({ state: "error", message: `Could not relaunch: ${e}` });
      }
    }
  }

  async function browse() {
    try {
      const picked = await openDialog({
        directory: true,
        multiple: false,
        title: "Choose data directory",
        defaultPath: dir || resolvedDir || undefined,
      });
      if (typeof picked === "string" && picked.trim()) {
        await applyDirectoryChange(picked.trim());
      }
    } catch (e) {
      setStatus({ state: "error", message: String(e) });
    }
  }

  async function reveal() {
    if (!resolvedDir) return;
    try {
      await revealItemInDir(resolvedDir);
    } catch (e) {
      setStatus({ state: "error", message: String(e) });
    }
  }

  const usingDefault = !dir;

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="text-base">Data Directory</CardTitle>
        <CardDescription>
          Root folder for all files generated by Meridian — sprint reports,
          templates, skills, and meetings. Defaults to the app data location if
          unset.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="space-y-1.5">
          <Label>Directory path</Label>
          <div className="flex gap-2 items-center">
            <div
              className={cn(
                "flex-1 rounded-md border border-input bg-muted/40 px-3 py-1.5 text-sm font-mono break-all min-h-9 flex items-center",
                usingDefault && "italic text-muted-foreground",
              )}
            >
              {dir || "Using default app data location"}
            </div>
            <Button
              onClick={browse}
              disabled={status.state === "loading"}
              size="sm"
              variant="outline"
            >
              {status.state === "loading" ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <>
                  <FolderOpen className="h-4 w-4 mr-1.5" />
                  Browse…
                </>
              )}
            </Button>
            {!usingDefault && (
              <Button
                onClick={() => applyDirectoryChange("")}
                disabled={status.state === "loading"}
                size="sm"
                variant="ghost"
              >
                Use default
              </Button>
            )}
          </div>
        </div>
        {resolvedDir && (
          <div className="flex items-center gap-2">
            <p className="text-xs text-muted-foreground font-mono break-all flex-1">
              Active: {resolvedDir}
            </p>
            <Button
              onClick={reveal}
              size="sm"
              variant="ghost"
              className="shrink-0"
            >
              <FolderOpen className="h-4 w-4 mr-1.5" />
              Open in Finder
            </Button>
          </div>
        )}
        {status.state === "success" && (
          <p className="text-xs text-emerald-600 flex items-center gap-1">
            <CheckCircle className="h-3 w-3" /> {status.message}
          </p>
        )}
        {status.state === "error" && (
          <p className="text-xs text-destructive flex items-center gap-1">
            <AlertCircle className="h-3 w-3" /> {status.message}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
